version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "node_postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  app:
    build: .
    depends_on:
      - redis
    ports:
      - "3000:3000"